FROM ubuntu:18.04

RUN set -xe \
  && apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y python3-pip python3-dev curl \
  && apt-get clean

RUN pip3 install --upgrade pip && \
    pip3 install --no-cache-dir pyyaml && \
    pip3 install --no-cache-dir requests && \
    pip3 install --no-cache-dir mysql-connector-python

WORKDIR /exchange-pwd
